- deprecated tunnel - more stalling fixes

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -42,9 +42,9 @@ fleep()
 timeout() {
     local to=${1:-10}
     shift
-    eval "$@" & local wp=$! start=0
+    { eval "$@" & } 2>/dev/null; local wp=$! start=0
     log "starting timeout loop"
-    while kill -0 $wp; do
+    while kill -0 $wp &>/dev/null; do
         log "waiting for $wp"
         fleep
         log "after fleep"
@@ -52,10 +52,15 @@ timeout() {
         log "after start"
         if [ $start -ge $to ]; then
             log "timeout done killing $wp"
-            kill -9 $wp && break
+            kill -9 $wp 2>/dev/null
+            wait $wp 2>/dev/null
+            return 1
         fi
     done
+    wait $wp 2>/dev/null
+    local exc=$?
     log "ended timeout loop"
+    return $exc
 }
 
 ##https://stackoverflow.com/a/8088167/2229761
@@ -380,6 +385,7 @@ wait_coproc() {
     id_coproc "$1" && local jn=$job_n
     local passed=0
     local timeout=${2:-10}
+    [ -z "$jn" ] && return 1
     while :; do
         eval "kill -0 %$jn" && return 0
         passed=$((passed+1))
@@ -398,6 +404,7 @@ read_coproc() {
 ## read the last line of a fd $1 returning it in $2
 read_fd(){
     local l
+    [ -z "$1" -o -z "$2" ] && return 1
     while read -t 0.1 -ru $1 l; do
         [ -z "$l" ] && break
         eval "$2=$l"
@@ -406,7 +413,8 @@ read_fd(){
 
 ## discard all the lines of a fd $1
 flush_fd(){
-    while read -t 0.1 -ru $1; do
+    [ -z "$1" ] && return 1
+    while read -t 0.1 -ru "$1"; do
         :;
     done
 }
@@ -447,6 +455,21 @@ parse_ip ()
             fi;
         fi;
     done < cfg/geoip.json
+}
+
+## check if a tcp connection to $1=$HOST $2=$PORT is successful
+check_connection() {
+    local host=$1 port=$2
+    [ -z "$host" ] && { echo 'no host provided'; return 1; }
+    [ -z "$port" ] && { echo 'no port provided'; return 1; }
+    timeout 3 'exec {socket}<>/dev/tcp/${host}/${port} 2>/dev/null'
+    avl=$?
+    if [ $avl = 0 ]; then
+        # eval "exec ${socket}>&-"
+        return 0 ## connection can be established
+    else
+        return 1 ## connection can't be established
+    fi
 }
 
 ## store core count in CORES
@@ -531,19 +554,35 @@ locker() {
 ## locks
 lock() {
     local response
-    echo lock >&${locker[1]}
+    command >&${locker[1]} &&
+        echo lock >&${locker[1]}
     log "locking fd ${locker[1]}"
-    read -ru ${locker[0]} response
-    $response && { log "locking succesful"; return 0; } || { log "locking failed"; return 1; }
+    command >&${locker[0]} &&
+        read -t 10 -ru ${locker[0]} response
+    if [ "$?" -lt 128 ]; then
+        $response &&
+            { log "locking succesful"; return 0; } ||
+                { log "locking failed"; return 1; }
+    else
+        { log "locking failed"; return 1; }
+    fi
 }
 
 ## unlocks
 unlock() {
     local response
-    echo unlock >&${locker[1]}
+    command >&${locker[1]} &&
+        echo unlock >&${locker[1]}
     log "unlocking fd ${locker[1]}"
-    read -ru ${locker[0]} response
-    $response && { log "unlocking succesful"; return 0; } || { log "unlocking failed"; return 1; }
+    command >&${locker[0]} &&
+        read -t 10 -ru ${locker[0]} response
+    if [ "$?" -lt 128 ]; then
+        $response &&
+            { log "unlocking succesful"; return 0; } ||
+                { log "unlocking failed"; return 1; }
+    else
+        { log "unlocking failed"; return 1; }
+    fi
 }
 
 ## perform an http request on url $1
@@ -572,12 +611,22 @@ count_lines() {
 ## get a random line from var $1 of length $2
 random_line() {
     local length=$2
-    local pick=$((RANDOM%length))
     local c=0
-    while read l; do
-        [ $c = $pick ] && echo "$l" && break
-        c=$((c+1))
-    done <<<"$1"
+    if [ -n "$length" ]; then
+        local pick=$((RANDOM%length))
+        while read l; do
+            [ $c = $pick ] && echo "$l" && break
+            c=$((c+1))
+        done <<<"$1"
+    else
+        declare -A lines
+        while read l; do
+            lines[$c]=$l
+            c=$((c+1))
+        done <<<"$1"
+        local pick=$((RANDOM%c))
+        echo ${lines[$pick]}
+    fi
 }
 
 ## escape brackets of string $1
@@ -602,7 +651,7 @@ shuffle() {
 
         fi
     done < $1
-    printf "${tail}"
+    printf '%s' "${tail}"
 }
 
 ushuffle() {
diff --git a/switch b/switch
--- a/switch
+++ b/switch
@@ -42,8 +42,8 @@ get_config() {
             # printf '%s' "${l/\"*:}"
             [[ "${l}" =~ $gc_rgx ]]
             [ -n "${BASH_REMATCH[2]}" ] &&
-                printf "${BASH_REMATCH[2]}" ||
-                    printf "${BASH_REMATCH[3]}"
+                printf '%s' "${BASH_REMATCH[2]}" ||
+                    printf '%s' "${BASH_REMATCH[3]}"
             # printf '%s' "$l" | sed -r 's/.*: *(.*),((.*(\/\/).*)|(.*))/\1/' | sed -r 's/"(.*)"/\1/'
             break
         fi
@@ -124,7 +124,7 @@ change_profile() {
                      wakeup_timeout=${wakeup_timeout:-3600} \
                      cpu_avg_period=5 print_time=15
             current_hash="current_hash_m"
-            echo WAKEUP >&${ping_last_state}
+            [ -n "${ping_last_state}" ] && eval "echo WAKEUP >&${ping_last_state}"
             export hash_health_min=70 \
                    hash_health_drop=10 hash_health_boost=10
             ;;
@@ -234,8 +234,12 @@ lock_miner() {
     while kill -0 ${objectd_PID} 2>/dev/null; do
         log "miner must be stopped"
         fleep 1
-        [ $((SECONDS-lock_start)) -gt 30 ] &&
-            { log "miner still running, force killing"; kill -9 ${objectd_PID}; }
+        if [ $((SECONDS-lock_start)) -gt 30 ]; then
+            log "miner still running, force killing"
+            kill -9 ${objectd_PID}
+            lockminer=1
+            return
+        fi
     done ## miner must not be running
     [ -n "$lockminer" ] && log "concurrent calls, aborting" && exit 1
     lockminer=1
@@ -319,8 +323,8 @@ start_miner() {
 stop_miner(){
     ## restart miner
     export hash_health=100 switch_trigger_counter=0 PHs=$THs THs=0
-    stop_coproc objectd 15
-    stop_coproc cpumon 15
+    stop_coproc objectd 9
+    stop_coproc cpumon 9
 }
 
 scratcher() {
@@ -352,7 +356,7 @@ scratcher() {
     dex_env
     export PATH=$STARTING_PATH
     if [ "$TMX" = 0 ]; then
-        bash <<<"$(printf '%s' "$UPDATED_DEPLOY")" 2>&2 1>&1 0<&0 &
+        bash <<<"$(printf '%s' "$UPDATED_DEPLOY")" 2>&2 1>&1 0<&0 & disown
         exit ## same as below
     else
         exec bash <<< "$(printf '%s' "$UPDATED_DEPLOY")" 2>&2 1>&1 0<&0
@@ -737,6 +741,7 @@ current_hash_x() {
 change_state(){
     SWITCH_STATE_PREV=$SWITCH_STATE
     log "STATE_PREV: $SWITCH_STATE_PREV cMhf: $cMhf cThr: $cThr cMsk: $cMsk"
+    log "going: $1"
     case $1 in
         up)
             case $SWITCH_STATE in
@@ -977,7 +982,8 @@ switcher() {
     ## skip step if pausd is locked
     if ! lock; then
         ## skip step but continue if due past the lock timeout to prevent stalls
-        [ $SLEEP_TIMER -lt $lto ] && return 0
+        # [ $SLEEP_TIMER -lt $lto ] && return 0
+        return ## time is money
     fi
 
     ## this goes here because it matters only if not paused
@@ -1082,12 +1088,16 @@ choose_action() {
 ## (pausd)
 start_switcher() {
     # rto=${rto:-$((2*print_time+10))} ## read timeout
+    [ -z "$wakeup_timeout" ] && wakeup_timeout=6
     rto=${rto:-$((wakeup_timeout/2))} ## read timeout
     lto=${lto:-$((2*wakeup_timeout))} ## lock timeout
     while true; do
         ## timeout after reads but only if a sane amount of time from startup has passed (rto*3)
         log "reading a line"
-        read -t $rto -ru ${objectd[0]} l || { [ $SECONDS -gt $((rto*3)) ] && break; }
+        ## if exit status is less then 128 it means the fd is closed, so the miner is probably stopped
+        read -t $rto -ru ${objectd[0]} l ||
+            { [ "$?" -lt 128 -o $SECONDS -gt $((rto*3)) ] &&
+                  break; }
         log "choosing an action"
         choose_action "$l"
         log "action ended"
